name: arcdocs-jb
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pandas=1.0.5
  - jupyterlab
  - matplotlib
  - pip=20
  - pip:
    - jupyter-book==0.7.1
    - sphinx-book-theme==0.0.30
    - ghp-import
